#!/usr/bin/env perl      

#version 0.9.3	Script Created
#version 0.9.3	Script to write out tables for R, replacement for doing with perl (this is over 25X more effecient)

use Getopt::Long;
use Data::Dumper;
use PDL::IO::HDF5;