
import argparse
import json
from pyEFI import BioHMMLogo

def convert_hmm_to_skylign_json(hmm_path, output_json_path, output_png_path):
    """
    Convert the HMM into a JSON output for Skylign and generate a raster image weblogo that looks
    like the output from Skylign.

    Parameters
    ----------
        hmm_path
            path to a hmm file generated by `hmmbuild`
        output_json_path
            path to the output JSON file containing Skylign data
        output_png_path
            path to the output raster image
    """
    logo = BioHMMLogo(hmm_path)
    logo_json = logo.as_json()
    with open(output_json_path, "w") as fh:
        fh.write(logo_json)
    logo_png = logo.as_png()
    logo_png.save(output_png_path)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Convert HMM output from HMMER into a JSON structure that can be used by Skylign for visualization")
    parser.add_argument("--hmm", required=True, type=str, help="Path to the input HMM file")
    parser.add_argument("--json", required=True, type=str, help="Path to the output JSON file")
    parser.add_argument("--png", required=True, type=str, help="Path to the output PNG file")
    args = parser.parse_args()
    convert_hmm_to_skylign_json(args.hmm, args.json, args.png)
