#!/bin/env perl

use strict;
use warnings;

use Data::Dumper;
use Getopt::Long;
use FindBin;

use lib "$FindBin::Bin/../../../lib";

use EFI::Annotations::Fields qw(:source);
use EFI::Import::Config::FastaImport;
use EFI::Import::Logger;
use EFI::Sequence::Collection;




my $logger = new EFI::Import::Logger();

my $optionParser = new EFI::Import::Config::FastaImport();
my ($status, $help) = $optionParser->validateOptions();

if ($help) {
    print "$help\n";
    exit(not $status); # if error, status is 0, so exit non zero to indicate to shell that there was a problem
}

my $config = $optionParser->getOptions();




# A mapping of line number in the original input FASTA file to sequence ID
my $lineMapping = loadMappingFile($config->{seq_mapping_file});

# All IDs come in the sequence ID list and metadata file, both those sourced from the FASTA file
# and those IDs added by family addition
my $seqCollection = new EFI::Sequence::Collection();
$seqCollection->load($config->{sequence_meta_file});
my @seqIds = $seqCollection->getSequenceIds();

# filteredSeqIds is used to exclude any IDs/sequences in the FASTA file that were excluded due to
# filtering in a prior step.
my %filteredSeqIds = map { $_ => 1 } @seqIds;


open my $in, "<", $config->{uploaded_fasta} or die "Unable to read input fasta file $config->{uploaded_fasta}: $!";
open my $out, ">", $config->{output_sequence_file} or die "Unable to write to output fasta file $config->{output_sequence_file}: $!";

my $lineNum = 0;
my $isValidSeq = 0;
while (my $line = <$in>) {
    if ($line =~ m/^>/) {
        my $mappedId = $lineMapping->{$lineNum};
        # If the header was valid and the ID wasn't filtered out in a previous step
        if ($mappedId and $filteredSeqIds{$mappedId}) {
            $out->print(">$lineMapping->{$lineNum}\n");
            $isValidSeq = 1;
        } else {
            $isValidSeq = 0;
        }
    } elsif ($isValidSeq) {
        # Print the current line from user-specified FASTA file
        $out->print($line);
    }
    $lineNum++;
}

close $out;
close $in;












#
# loadMappingFile
#
# Load the mapping file that maps sequence ID (UniProt or unknown) to line number in the original
# FASTA file.
#
# Parameters:
#    $file - path to mapping file
#
# Returns:
#    hash ref with key being line number and value being sequence ID
#
sub loadMappingFile {
    my $file = shift;

    my $mapping = {};

    open my $fh, "<", $file or die "Unable to read mapping file $file: $!";

    my $headerLine = <$fh>;

    while (my $line = <$fh>) {
        chomp $line;
        next if $line =~ m/^\s*$/ or $line =~ m/^#/;
        my ($id, $lineNum) = split(m/\t/, $line);
        $mapping->{$lineNum} = $id;
    }

    close $fh;

    return $mapping;
}




1;
__END__

=head1 import_fasta.pl

=head2 NAME

B<import_fasta.pl> - import user-specified FASTA sequences into a form usable by the EST pipeline

=head2 SYNOPSIS

    import_fasta.pl --uploaded-fasta <FILE> [--seq-mapping-file <FILE> --sequence-meta-file <FILE>
        --output-sequence-file <FILE> --sequence-ids-file <FILE>]

=head2 DESCRIPTION

This script reformats a user-specified FASTA sequence file into a form that is usable by the
EST pipeline.  Any sequence IDs from the FASTA header that were not identified are assigned a
unique ID in the unknown ID format (see B<EFI::Sequence::Type>).

An example of a user-specified input file:

    >|tr|B0SS77|Leptospira biflexa
    ABCDEFG

    >B0SS75 Leptospira biflexa serovar Patoc
    ABCDEFG

    >OtherID
    >Life-42
    ABCDEFG

    >ABZ97962.1
    ABCDEFG

Running this script with that file would result the following output file:

    >B0SS77
    ABCDEFG

    >B0SS75
    ABCDEFG

    >ZZZZZ0
    ABCDEFG

    >B0SS72
    ABCDEFG


=head3 Arguments

=over

=item C<--uploaded-fasta-file> (required)

The path to the user-specified FASTA file.

=item C<--seq-mapping-file> (required, default value)

This file is a two column format file with a header line, where the first column is the UniProt
or unknown ID and the second column is the line number where the corresponding sequence header
is located in the C<--user-uploaded-file> file.

This file is generated by C<get_sequence_ids.pl> in a prior step which outputs a file that maps
line numbers in the original user-specified FASTA file to anonymous sequence identifiers.
Defaults to C<seq_mapping.tab> in the current directory.

=item C<--sequence-meta-file> (required, default value)

Path to the file containing sequence metadata (e.g. mapping sequence ID to metadata such as
the original ID from the fasta).  If sequences are in the input FASTA (and sequence mapping file)
but are not in this file then they are not output.  This occurs if the sequence was filtered out
in a prior step (e.g. to remove fragments).
Defaults to C<sequence_metadata.tab> in the current directory.

=item C<--output-sequence-file> (required, default value)

The path to an output file containing the sequences from the input FASTA file.  The sequences are
reformatted and renumbered as necessary.  If sequences were removed by filtering in a prior step
then they are not included in the output.
Defaults to C<all_sequences.tab> in the current directory.

=item C<--sequence-ids-file> (required, default value)

The path to an output file that contains any IDs that were provided to this script via the metadata
file but were not in the original FASTA file.  This occurs when a family is added to a FASTA
import.  This file is used later in the EST pipeline to retrieve non-FASTA sequences.
Defaults to C<sequence_ids.tab> in the current directory.

=back

